- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Create new S3 Bucket
      aws_s3:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        bucket: la-ansible-dem-bucket-with-unique-name
        mode: create
    - name: Add file to bucket
      aws_s3:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        bucket: la-ansible-dem-bucket-with-unique-name
        mode: put
        object: /testfile.txt
        src: /home/ansible/testfile.txt
